[package]
name = "vibechat"
version = "0.1.0"
description = "VibeChat 桌面壳，用于加载本地 Tinode Web"
authors = ["VibeChat"]
edition = "2021"

[lib]
name = "vibechat_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
